# Generated by Django 2.2.9 on 2020-01-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_data', models.DateTimeField(auto_now=True, null=True)),
                ('category_name', models.CharField(choices=[(1, 'Do now'), (2, 'Do tomorrow'), (3, 'Do soon'), (4, 'Do when you get some extra time')], max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
