# Generated by Django 2.2.9 on 2020-01-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('1', 'Do now'), ('2', 'Do tomorrow'), ('3', 'Do soon'), ('4', 'Do when you get some extra time')], max_length=100, unique=True),
        ),
    ]
